"use client"

import { motion } from "framer-motion"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { AnimatedBackground } from "@/components/ui/animated-background"
import { Footer } from "@/components/ui/footer"
import { useEffect } from "react"

export default function TermsPage() {
  // Ensure theme is correctly applied when loading the page
  useEffect(() => {
    // Check theme saved in localStorage
    const savedTheme = localStorage.getItem("theme")

    // Apply theme to document
    if (savedTheme === "dark") {
      document.documentElement.classList.add("dark")
    } else {
      document.documentElement.classList.remove("dark")
    }
  }, [])

  return (
    <div className="flex flex-col min-h-screen">
      <AnimatedBackground />

      <main className="flex-1 container max-w-4xl mx-auto py-8 px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-md rounded-xl shadow-xl p-6 border border-blue-200 dark:border-blue-900"
        >
          <div className="mb-6">
            <Link
              href="/"
              className="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 transition-colors"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Nahara
            </Link>
          </div>

          <div className="prose prose-blue dark:prose-invert max-w-none">
            <h1 className="text-3xl font-bold text-blue-700 dark:text-blue-300 mb-6 flex items-center">
              🧾 Terms and Conditions
            </h1>

            <div className="text-sm text-blue-800 dark:text-blue-200 mb-8">
              <p>
                <strong>Effective Date:</strong> April 19, 2025
              </p>
              <p>
                <strong>Site Owner:</strong> MikeDevQh - Michael
              </p>
              <p>
                <strong>Website:</strong>{" "}
                <a href="https://nahara-ai.vercel.app" className="text-blue-600 dark:text-blue-400 hover:underline">
                  https://nahara-ai.vercel.app
                </a>
              </p>
            </div>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">1. Acceptance of Terms</h2>
              <p className="mb-4">
                By accessing and using this website, you agree to comply with these Terms and Conditions, as well as all
                applicable laws and regulations. If you do not agree with any of these terms, please do not use the
                site.
              </p>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">2. Use of the Site</h2>
              <p className="mb-4">
                Access to this platform is permitted only for personal, informational, or recreational purposes. The
                user agrees not to use the site for illegal, defamatory, fraudulent activities, or any actions that may
                affect the service's operation.
              </p>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">3. AI-Generated Content</h2>
              <p className="mb-2">
                This site offers a conversational experience with an artificial intelligence called Nahara, which
                generates content in real-time based on user inputs.
              </p>
              <p className="mb-2">
                <strong>Important:</strong>
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>
                  Content generated by Nahara is automatic and should not be considered professional advice (legal,
                  medical, psychological, etc.).
                </li>
                <li>The user is responsible for how they use the generated information.</li>
              </ul>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">4. Intellectual Property</h2>
              <p className="mb-2">
                All content on this site, including but not limited to source code, images, styles, interface, texts,
                and visual elements, is the property of MikeDevQh - Michael, unless otherwise indicated.
              </p>
              <p className="mb-2">Copyright (c) 2025 MikeDevQh - Michael. All rights reserved.</p>
              <p className="mb-2">
                This repository and website contain source code, images, and other resources created by the author.
              </p>

              <p className="mb-2">
                <strong>Not permitted:</strong>
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Copying, modifying, or redistributing the source code.</li>
                <li>Using images from this repository or site in other projects, sites, or products.</li>
                <li>Using this content for commercial or personal purposes without express written authorization.</li>
              </ul>

              <p className="mb-2">
                <strong>Permitted:</strong>
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>
                  Mentioning or publicly sharing this project or website, as long as credit to the author is respected
                  and linked directly to the original site.
                </li>
                <li>
                  Including this project in lists, recommendations, or compilations, as long as its content is not
                  replicated or its resources used directly.
                </li>
              </ul>

              <p className="mb-2">
                This project is not under a free or open-source license. Any unauthorized use will be considered a
                copyright violation and may be subject to legal action, including takedown requests (DMCA).
              </p>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">5. External Links</h2>
              <p className="mb-4">
                This site may contain links to other websites. We are not responsible for the content or privacy
                policies of such third-party sites.
              </p>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">
                6. Limitation of Liability
              </h2>
              <p className="mb-4">
                We do not guarantee the continuous availability of the site, nor the absence of errors in the content
                generated by the AI. Use of the site is at the user's own risk.
              </p>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">7. Modifications</h2>
              <p className="mb-4">
                We reserve the right to update or modify these terms at any time, without prior notice. It is
                recommended to periodically review this section to stay informed of possible changes.
              </p>
            </section>

            <section className="mb-6">
              <h2 className="text-xl font-semibold text-blue-600 dark:text-blue-400 mb-3">8. Contact</h2>
              <p className="mb-4">
                If you have questions about these terms or wish to request authorization for content use, you can write
                to:
                <br />📧{" "}
                <a
                  href="mailto:contacto.nahara.ai@gmail.com"
                  className="text-blue-600 dark:text-blue-400 hover:underline"
                >
                  contacto.nahara.ai@gmail.com
                </a>
              </p>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  )
}
