export default {
  'code[class*="language-"]': {
    color: '#e0eaff',
    background: 'none',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '1em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    tabSize: '4',
    hyphens: 'none',
    textShadow: 'none',
  },
  'pre[class*="language-"]': {
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    borderRadius: '0.5rem',
    backgroundColor: '#0c1027',
    backgroundImage: 'linear-gradient(to bottom right, #121E58, #1b1c3b)',
  },
  ':not(pre) > code[class*="language-"]': {
    backgroundColor: '#1c213a',
    color: '#e0eaff',
    padding: '0.1em 0.3em',
    borderRadius: '0.3em',
  },
  comment: { color: '#7a88b6' },
  prolog: { color: '#7a88b6' },
  doctype: { color: '#7a88b6' },
  cdata: { color: '#7a88b6' },
  punctuation: { color: '#9aa2d8' },
  property: { color: '#72f1b8' },
  selector: { color: '#72f1b8' },
  'attr-name': { color: '#72f1b8' },
  string: { color: '#c084fc' },
  regex: { color: '#c084fc' },
  'attr-value': { color: '#c084fc' },
  function: { color: '#60a5fa' },
  'function-name': { color: '#60a5fa' },
  keyword: { color: '#93c5fd' },
  'class-name': { color: '#93c5fd' },
  atrule: { color: '#93c5fd' },
  builtin: { color: '#93c5fd' },
  number: { color: '#38bdf8' },
  boolean: { color: '#38bdf8' },
  operator: { color: '#7dd3fc' },
  inserted: { color: '#34d399' },
  important: { color: '#facc15' },
};

