export default {
    'code[class*="language-"]': {
    color: '#3f468c', 
    background: 'none',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '1em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    tabSize: '4',
    hyphens: 'none',
    textShadow: 'none',
  },
  'pre[class*="language-"]': {
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    borderRadius: '0.5rem',
    backgroundColor: '#f7f7ff',
    backgroundImage: 'linear-gradient(to bottom right, #e8ecff, #ffffff)',
  },
  ':not(pre) > code[class*="language-"]': {
    backgroundColor: '#e7edff',
    color: '#3f468c',
    padding: '0.1em 0.3em',
    borderRadius: '0.3em',
  },
  comment: { color: '#8291c6', fontStyle: 'italic' },
  prolog: { color: '#8291c6', fontStyle: 'italic' },
  doctype: { color: '#8291c6', fontStyle: 'italic' },
  cdata: { color: '#8291c6', fontStyle: 'italic' },
  punctuation: { color: '#5c60a8' },
  namespace: { color: '#b26cd9' },
  deleted: { color: '#b26cd9' },
  symbol: { color: '#b26cd9' },
  constant: { color: '#b26cd9' },
  property: { color: '#3b82f6' },
  selector: { color: '#3b82f6' },
  'attr-name': { color: '#3b82f6' },
  boolean: { color: '#2563eb' },
  number: { color: '#2563eb' },
  string: { color: '#9333ea' },
  char: { color: '#9333ea' },
  regex: { color: '#9333ea' },
  'attr-value': { color: '#9333ea' },
  variable: { color: '#9333ea' },
  operator: { color: '#0ea5e9' },
  entity: { color: '#0ea5e9', cursor: 'help' },
  url: { color: '#0ea5e9' },
  atrule: { color: '#3f468c', fontWeight: 'bold' },
  keyword: { color: '#3f468c', fontWeight: 'bold' },
  'class-name': { color: '#3f468c', fontWeight: 'bold' },
  builtin: { color: '#3f468c', fontWeight: 'bold' },
  'selector-id': { color: '#3f468c', fontWeight: 'bold' },
  'selector-class': { color: '#3f468c', fontWeight: 'bold' },
  function: { color: '#2563eb' },
  'function-name': { color: '#2563eb' },
  important: { color: '#d97706', fontWeight: 'bold' },
  inserted: { color: '#10b981' },
};
  